/**
 * 35 Languages Translations for Cookie Banner & Preferences
 */

export interface TranslationSet {
  name: string;
  nativeName: string;
  title: string;
  description: string;
  acceptAll: string;
  rejectAll: string;
  customize: string;
  savePreferences: string;
  necessary: string;
  necessaryDesc: string;
  analytics: string;
  analyticsDesc: string;
  marketing: string;
  marketingDesc: string;
  preferences: string;
  preferencesDesc: string;
  doNotSell: string;
  policyLinkText: string;
}

export const SUPPORTED_LANGUAGES: Record<string, TranslationSet> = {
  en: {
    name: 'English',
    nativeName: 'English',
    title: 'We value your privacy 🌿',
    description: 'Greenwave Society uses cookies to enhance your browsing experience, analyze site traffic, and personalize content in compliance with GDPR & CCPA.',
    acceptAll: 'Accept All',
    rejectAll: 'Reject Non-Essential',
    customize: 'Customize Settings',
    savePreferences: 'Save Preferences',
    necessary: 'Strictly Necessary',
    necessaryDesc: 'Required for core website security, authentication, and core performance.',
    analytics: 'Analytics & Performance',
    analyticsDesc: 'Helps us understand how visitors interact with our environmental programs.',
    marketing: 'Marketing & Outreach',
    marketingDesc: 'Used to measure campaign reach and support our sustainability mission.',
    preferences: 'Functional Preferences',
    preferencesDesc: 'Stores your preferred language, region, and visual settings.',
    doNotSell: 'Do Not Sell or Share My Personal Information (CCPA)',
    policyLinkText: 'Privacy Policy',
  },
  sw: {
    name: 'Swahili',
    nativeName: 'Kiswahili',
    title: 'Tunathamini faragha yako 🌿',
    description: 'Greenwave Society inatumia vidakuzi ili kuboresha uzoefu wako, kuchanganua trafiki ya tovuti, na kubinafsisha maudhui kulingana na GDPR & CCPA.',
    acceptAll: 'Kubali Yote',
    rejectAll: 'Kataa Yasiyo ya Lazima',
    customize: 'Badilisha Mipangilio',
    savePreferences: 'Hifadhi Mipangilio',
    necessary: 'Ya Lazima Kabisa',
    necessaryDesc: 'Inahitajika kwa usalama wa kimsingi wa tovuti na utendakazi.',
    analytics: 'Uchanganuzi na Utendaji',
    analyticsDesc: 'Inatusaidia kuelewa jinsi wageni wanavyotangamana na mipango yetu ya mazingira.',
    marketing: 'Uuzaji na Ufikiaji',
    marketingDesc: 'Inatumika kupima ufikiaji wa kampeni na kuunga mkono dhamira yetu.',
    preferences: 'Mapendeleo ya Kazi',
    preferencesDesc: 'Inahifadhi lugha na mipangilio yako unayoipendelea.',
    doNotSell: 'Usiuze au Kushiriki Taarifa Zangu za Kibinafsi (CCPA)',
    policyLinkText: 'Sera ya Faragha',
  },
  es: {
    name: 'Spanish',
    nativeName: 'Español',
    title: 'Valoramos tu privacidad 🌿',
    description: 'Greenwave Society utiliza cookies para mejorar su experiencia, analizar el tráfico y personalizar contenido conforme a GDPR y CCPA.',
    acceptAll: 'Aceptar todo',
    rejectAll: 'Rechazar no esenciales',
    customize: 'Personalizar',
    savePreferences: 'Guardar preferencias',
    necessary: 'Estrictamente necesarias',
    necessaryDesc: 'Necesarias para la seguridad y funcionamiento básico.',
    analytics: 'Análisis y rendimiento',
    analyticsDesc: 'Nos ayuda a entender cómo interactúan los visitantes.',
    marketing: 'Marketing',
    marketingDesc: 'Utilizado para medir el alcance de nuestras campañas.',
    preferences: 'Preferencias',
    preferencesDesc: 'Guarda su idioma y configuración preferida.',
    doNotSell: 'No vender ni compartir mi información personal',
    policyLinkText: 'Política de privacidad',
  },
  fr: {
    name: 'French',
    nativeName: 'Français',
    title: 'Nous respectons votre vie privée 🌿',
    description: 'Greenwave Society utilise des cookies pour améliorer votre expérience, analyser le trafic et personnaliser le contenu conformément au RGPD.',
    acceptAll: 'Tout accepter',
    rejectAll: 'Refuser le non essentiel',
    customize: 'Personnaliser',
    savePreferences: 'Enregistrer',
    necessary: 'Strictement nécessaires',
    necessaryDesc: 'Requis pour la sécurité et les fonctionnalités de base.',
    analytics: 'Analytique & Performance',
    analyticsDesc: 'Nous aide à comprendre l’utilisation du site.',
    marketing: 'Marketing',
    marketingDesc: 'Utilisé pour mesurer l’impact de nos campagnes.',
    preferences: 'Préférences',
    preferencesDesc: 'Enregistre vos paramètres de langue et région.',
    doNotSell: 'Ne pas vendre mes informations personnelles',
    policyLinkText: 'Politique de confidentialité',
  },
  de: {
    name: 'German',
    nativeName: 'Deutsch',
    title: 'Wir schätzen Ihre Privatsphäre 🌿',
    description: 'Greenwave Society verwendet Cookies, um Ihre Erfahrung zu verbessern, den Datenverkehr zu analysieren und Inhalte DSGVO-konform anzupassen.',
    acceptAll: 'Alle akzeptieren',
    rejectAll: 'Nicht essenzielle ablehnen',
    customize: 'Einstellungen anpassen',
    savePreferences: 'Einstellungen speichern',
    necessary: 'Notwendig',
    necessaryDesc: 'Erforderlich für Sicherheit und Grundfunktionen.',
    analytics: 'Analyse & Leistung',
    analyticsDesc: 'Hilft uns zu verstehen, wie Besucher die Website nutzen.',
    marketing: 'Marketing',
    marketingDesc: 'Dient der Messung unserer Kampagnenreichweite.',
    preferences: 'Präferenzen',
    preferencesDesc: 'Speichert Ihre bevorzugte Sprache und Einstellungen.',
    doNotSell: 'Meine persönlichen Daten nicht verkaufen',
    policyLinkText: 'Datenschutzerklärung',
  },
  it: {
    name: 'Italian',
    nativeName: 'Italiano',
    title: 'Valorizziamo la tua privacy 🌿',
    description: 'Greenwave Society utilizza i cookie per migliorare la tua esperienza e analizzare il traffico in conformità con il GDPR.',
    acceptAll: 'Accetta tutti',
    rejectAll: 'Rifiuta non essenziali',
    customize: 'Personalizza',
    savePreferences: 'Salva preferenze',
    necessary: 'Strettamente necessari',
    necessaryDesc: 'Necessari per la sicurezza e la funzionalità del sito.',
    analytics: 'Analisi e prestazioni',
    analyticsDesc: 'Ci aiuta a comprendere come gli utenti interagiscono.',
    marketing: 'Marketing',
    marketingDesc: 'Utilizzato per misurare l’impatto delle nostre campagne.',
    preferences: 'Preferenze',
    preferencesDesc: 'Salva la lingua e le impostazioni visive.',
    doNotSell: 'Non vendere le mie informazioni personali',
    policyLinkText: 'Informativa sulla privacy',
  },
  pt: {
    name: 'Portuguese',
    nativeName: 'Português',
    title: 'Valorizamos a sua privacidade 🌿',
    description: 'Greenwave Society usa cookies para melhorar a navegação e analisar o tráfego em conformidade com o RGPD.',
    acceptAll: 'Aceitar todos',
    rejectAll: 'Rejeitar não essenciais',
    customize: 'Personalizar',
    savePreferences: 'Salvar preferências',
    necessary: 'Estritamente necessários',
    necessaryDesc: 'Necessários para a segurança e funções básicas.',
    analytics: 'Análise e Desempenho',
    analyticsDesc: 'Ajuda-nos a entender a interação dos visitantes.',
    marketing: 'Marketing',
    marketingDesc: 'Usado para medir o alcance das campanhas.',
    preferences: 'Preferências',
    preferencesDesc: 'Salva o seu idioma e preferências de exibição.',
    doNotSell: 'Não vender minhas informações pessoais',
    policyLinkText: 'Política de Privacidade',
  },
  nl: {
    name: 'Dutch',
    nativeName: 'Nederlands',
    title: 'Wij waarderen uw privacy 🌿',
    description: 'Greenwave Society gebruikt cookies om uw ervaring te verbeteren en het verkeer te analyseren conform de AVG.',
    acceptAll: 'Alles accepteren',
    rejectAll: 'Niet-essentiële weigeren',
    customize: 'Aanpassen',
    savePreferences: 'Voorkeuren opslaan',
    necessary: 'Strikt noodzakelijk',
    necessaryDesc: 'Vereist voor beveiliging en basisfunctionaliteit.',
    analytics: 'Analyse & Prestaties',
    analyticsDesc: 'Helpt ons te begrijpen hoe bezoekers de site gebruiken.',
    marketing: 'Marketing',
    marketingDesc: 'Gebruikt om het bereik van onze campagnes te meten.',
    preferences: 'Voorkeuren',
    preferencesDesc: 'Slaat uw voorkeurstaal en instellingen op.',
    doNotSell: 'Verkoop mijn persoonlijke gegevens niet',
    policyLinkText: 'Privacybeleid',
  },
  pl: {
    name: 'Polish',
    nativeName: 'Polski',
    title: 'Cenimy Twoją prywatność 🌿',
    description: 'Greenwave Society używa plików cookie do optymalizacji serwisu i analizy ruchu zgodnie z RODO.',
    acceptAll: 'Zaakceptuj wszystkie',
    rejectAll: 'Odrzuć opcjonalne',
    customize: 'Dostosuj',
    savePreferences: 'Zapisz preferencje',
    necessary: 'Niezbędne',
    necessaryDesc: 'Wymagane do bezpieczeństwa i działania strony.',
    analytics: 'Analityka i wydajność',
    analyticsDesc: 'Pomaga nam zrozumieć korzystanie z serwisu.',
    marketing: 'Marketing',
    marketingDesc: 'Służy do pomiaru skuteczności kampanii.',
    preferences: 'Preferencje',
    preferencesDesc: 'Zapisuje preferencje językowe i wizualne.',
    doNotSell: 'Nie sprzedawaj moich danych',
    policyLinkText: 'Polityka prywatności',
  },
  ru: {
    name: 'Russian',
    nativeName: 'Русский',
    title: 'Мы ценим вашу конфиденциальность 🌿',
    description: 'Greenwave Society использует куки для улучшения работы сайта и анализа трафика в соответствии с GDPR.',
    acceptAll: 'Принять все',
    rejectAll: 'Отклонить необязательные',
    customize: 'Настроить',
    savePreferences: 'Сохранить настройки',
    necessary: 'Строго необходимые',
    necessaryDesc: 'Необходимы для безопасности и базовой работы.',
    analytics: 'Аналитика и производительность',
    analyticsDesc: 'Помогают нам понимать взаимодействие посетителей.',
    marketing: 'Маркетинг',
    marketingDesc: 'Используются для оценки эффективности кампаний.',
    preferences: 'Предпочтения',
    preferencesDesc: 'Сохраняют язык и визуальные настройки.',
    doNotSell: 'Не продавать мою личную информацию',
    policyLinkText: 'Политика конфиденциальности',
  },
  zh: {
    name: 'Chinese',
    nativeName: '中文',
    title: '我们重视您的隐私 🌿',
    description: 'Greenwave Society 使用 Cookie 改善您的浏览体验、分析流量并个性化内容，符合 GDPR 和 CCPA 规定。',
    acceptAll: '接受全部',
    rejectAll: '拒绝非必要',
    customize: '自定义设置',
    savePreferences: '保存首选项',
    necessary: '必要 Cookie',
    necessaryDesc: '网站安全和基本功能所必需。',
    analytics: '分析与性能',
    analyticsDesc: '帮助我们了解访客如何使用网站。',
    marketing: '营销推广',
    marketingDesc: '用于衡量我们的环保宣传效果。',
    preferences: '功能偏好',
    preferencesDesc: '保存您的语言和显示偏好设置。',
    doNotSell: '请勿出售或共享我的个人信息 (CCPA)',
    policyLinkText: '隐私政策',
  },
  ja: {
    name: 'Japanese',
    nativeName: '日本語',
    title: 'プライバシーを尊重します 🌿',
    description: 'Greenwave Societyは、体験の向上、アクセス解析、コンテンツの最適化のためにクッキーを使用しています。',
    acceptAll: 'すべて同意',
    rejectAll: '非必須を拒否',
    customize: '設定をカスタマイズ',
    savePreferences: '設定を保存',
    necessary: '厳密に必要',
    necessaryDesc: 'ウェブサイトのセキュリティと基本機能に必要です。',
    analytics: '分析とパフォーマンス',
    analyticsDesc: '利用状況の把握と改善に役立ちます。',
    marketing: 'マーケティング',
    marketingDesc: 'キャンペーンの効果測定に使用されます。',
    preferences: '機能設定',
    preferencesDesc: '言語や表示設定を保存します。',
    doNotSell: '個人情報を販売・共有しないでください',
    policyLinkText: 'プライバシーポリシー',
  },
  ko: {
    name: 'Korean',
    nativeName: '한국어',
    title: '개인정보를 보호합니다 🌿',
    description: 'Greenwave Society는 GDPR 및 CCPA 준수를 위해 쿠키를 사용하여 사용자 경험을 개선하고 트래픽을 분석합니다.',
    acceptAll: '모두 동의',
    rejectAll: '비필수 거부',
    customize: '설정 맞춤화',
    savePreferences: '설정 저장',
    necessary: '필수 쿠키',
    necessaryDesc: '웹사이트 보안 및 기본 기능에 필요합니다.',
    analytics: '분석 및 성능',
    analyticsDesc: '방문자의 사이트 이용 방식을 이해하는 데 도움을 줍니다.',
    marketing: '마케팅',
    marketingDesc: '캠페인 도달 범위를 측정하는 데 사용됩니다.',
    preferences: '기능 환경설정',
    preferencesDesc: '선택한 언어 및 표시 설정을 저장합니다.',
    doNotSell: '내 개인정보 판매 및 공유 금지',
    policyLinkText: '개인정보 처리방침',
  },
  ar: {
    name: 'Arabic',
    nativeName: 'العربية',
    title: 'نحن نقدر خصوصيتك 🌿',
    description: 'تستخدم جمعية Greenwave ملفات تعريف الارتباط لتحسين تجربتك وتحليل الزيارات وفقًا للائحة GDPR وCCPA.',
    acceptAll: 'قبول الكل',
    rejectAll: 'رفض غير الضروري',
    customize: 'تخصيص الإعدادات',
    savePreferences: 'حفظ التفضيلات',
    necessary: 'ضرورية مطلقاً',
    necessaryDesc: 'مطلوبة للأمان الوظيفي والأساسي للموقع.',
    analytics: 'التحليلات والأداء',
    analyticsDesc: 'تساعدنا على فهم كيفية تفاعل الزوار.',
    marketing: 'التسويق',
    marketingDesc: 'تُستخدم لقياس مدى وصول حملاتنا البيئية.',
    preferences: 'التفضيلات الوظيفية',
    preferencesDesc: 'تحفظ اللغة والإعدادات المفضلة لديك.',
    doNotSell: 'لا تبيع أو تشارك معلوماتي الشخصية',
    policyLinkText: 'سياسة الخصوصية',
  },
  tr: {
    name: 'Turkish',
    nativeName: 'Türkçe',
    title: 'Gizliliğinize önem veriyoruz 🌿',
    description: 'Greenwave Society, deneyiminizi geliştirmek ve trafiği analiz etmek için çerezler kullanır.',
    acceptAll: 'Tümünü Kabul Et',
    rejectAll: 'Gerekli Olmayanları Reddet',
    customize: 'Ayarları Özelleştir',
    savePreferences: 'Tercihleri Kaydet',
    necessary: 'Kesinlikle Gerekli',
    necessaryDesc: 'Site güvenliği ve temel işlevler için gereklidir.',
    analytics: 'Analiz ve Performans',
    analyticsDesc: 'Ziyaretçilerin siteyi nasıl kullandığını anlamamıza yardımcı olur.',
    marketing: 'Pazarlama',
    marketingDesc: 'Kampanya erişimini ölçmek için kullanılır.',
    preferences: 'Tercihler',
    preferencesDesc: 'Tercih ettiğiniz dil ve görünüm ayarlarını saklar.',
    doNotSell: 'Kişisel Bilgilerimi Satma veya Paylaşma',
    policyLinkText: 'Gizlilik Politikası',
  },
  hi: {
    name: 'Hindi',
    nativeName: 'हिन्दी',
    title: 'हम आपकी गोपनीयता का सम्मान करते हैं 🌿',
    description: 'Greenwave Society आपके अनुभव को बेहतर बनाने और ट्रैफ़िक विश्लेषण के लिए कुकीज़ का उपयोग करती है।',
    acceptAll: 'सभी स्वीकार करें',
    rejectAll: 'अनावश्यक अस्वीकार करें',
    customize: 'सेटिंग्स अनुकूलित करें',
    savePreferences: 'प्राथमिकताएं सहेजें',
    necessary: 'अत्यंत आवश्यक',
    necessaryDesc: 'सुरक्षा और बुनियादी कार्यों के लिए आवश्यक।',
    analytics: 'विश्लेषण और प्रदर्शन',
    analyticsDesc: 'यह समझने में मदद करता है कि आगंतुक कैसे सहभागिता करते हैं।',
    marketing: 'मार्केटिंग',
    marketingDesc: 'अभियान की पहुंच मापने के लिए उपयोग किया जाता है।',
    preferences: 'कार्यात्मक प्राथमिकताएं',
    preferencesDesc: 'आपकी भाषा और प्राथमिकताएं सुरक्षित रखता है।',
    doNotSell: 'मेरी व्यक्तिगत जानकारी न बेचें (CCPA)',
    policyLinkText: 'गोपनीयता नीति',
  },
  sv: {
    name: 'Swedish',
    nativeName: 'Svenska',
    title: 'Vi värdesätter din integritet 🌿',
    description: 'Greenwave Society använder kakor för att förbättra din upplevelse och analysera trafik enligt GDPR.',
    acceptAll: 'Acceptera alla',
    rejectAll: 'Neka icke-nödvändiga',
    customize: 'Anpassa inställningar',
    savePreferences: 'Spara inställningar',
    necessary: 'Strikt nödvändiga',
    necessaryDesc: 'Krävs för säkerhet och grundläggande funktioner.',
    analytics: 'Analys och prestanda',
    analyticsDesc: 'Hjälper oss att förstå hur besökare använder webbplatsen.',
    marketing: 'Marknadsföring',
    marketingDesc: 'Används för att mäta kampanjers räckvidd.',
    preferences: 'Funktionella inställningar',
    preferencesDesc: 'Sparar ditt föredragna språk och inställningar.',
    doNotSell: 'Sälj inte min personliga information',
    policyLinkText: 'Integritetspolicy',
  },
  no: {
    name: 'Norwegian',
    nativeName: 'Norsk',
    title: 'Vi verdsetter ditt personvern 🌿',
    description: 'Greenwave Society bruker informasjonskapsler for å forbedre opplevelsen din og analysere trafikk.',
    acceptAll: 'Godta alle',
    rejectAll: 'Avvis ikke-nødvendige',
    customize: 'Tilpass innstillinger',
    savePreferences: 'Lagre innstillinger',
    necessary: 'Strengt nødvendige',
    necessaryDesc: 'Påkrevd for sikkerhet og grunnleggende funksjoner.',
    analytics: 'Analyse og ytelse',
    analyticsDesc: 'Hjelper oss med å forstå hvordan besøkende bruker siden.',
    marketing: 'Markedsføring',
    marketingDesc: 'Brukes til å måle kampanjerekkevidde.',
    preferences: 'Preferanser',
    preferencesDesc: 'Lagrer valgt språk og visningsinnstillinger.',
    doNotSell: 'Ikke selg min personlige informasjon',
    policyLinkText: 'Personvernerklæring',
  },
  da: {
    name: 'Danish',
    nativeName: 'Dansk',
    title: 'Vi værdsætter dit privatliv 🌿',
    description: 'Greenwave Society bruger cookies til at forbedre din oplevelse og analysere trafik i overensstemmelse med GDPR.',
    acceptAll: 'Accepter alle',
    rejectAll: 'Afvis ikke-nødvendige',
    customize: 'Tilpas indstillinger',
    savePreferences: 'Gem indstillinger',
    necessary: 'Strengt nødvendige',
    necessaryDesc: 'Nødvendigt for sikkerhed og grundlæggende funktioner.',
    analytics: 'Analyse og ydeevne',
    analyticsDesc: 'Hjælper os med at forstå besøgendes adfærd.',
    marketing: 'Markedsføring',
    marketingDesc: 'Bruges til at måle kampagnerækkevidde.',
    preferences: 'Præferencer',
    preferencesDesc: 'Gemmer dit foretrukne sprog og indstillinger.',
    doNotSell: 'Sælg ikke mine personlige oplysninger',
    policyLinkText: 'Privatlivspolitik',
  },
  fi: {
    name: 'Finnish',
    nativeName: 'Suomi',
    title: 'Arvostamme yksityisyyttäsi 🌿',
    description: 'Greenwave Society käyttää evästeitä parantaakseen käyttökokemustasi ja analysoidakseen liikennettä.',
    acceptAll: 'Hyväksy kaikki',
    rejectAll: 'Hylkää ei-välttämättömät',
    customize: 'Mukauta asetuksia',
    savePreferences: 'Tallenna asetukset',
    necessary: 'Ehdottoman välttämättömät',
    necessaryDesc: 'Vaaditaan turvallisuutta ja perustoimintoja varten.',
    analytics: 'Analyysi ja suorituskyky',
    analyticsDesc: 'Auttaa meitä ymmärtämään sivuston käyttöä.',
    marketing: 'Markkinointi',
    marketingDesc: 'Käytetään kampanjoiden kattavuuden mittaamiseen.',
    preferences: 'Asetukset',
    preferencesDesc: 'Tallentaa kielivalintasi ja asetuksesi.',
    doNotSell: 'Älä myy henkilötietojani',
    policyLinkText: 'Tietosuojaseloste',
  },
  el: {
    name: 'Greek',
    nativeName: 'Ελληνικά',
    title: 'Εκτιμούμε το απόρρητό σας 🌿',
    description: 'Η Greenwave Society χρησιμοποιεί cookies για τη βελτίωση της εμπειρίας σας σύμφωνα με το GDPR.',
    acceptAll: 'Αποδοχή όλων',
    rejectAll: 'Απόρριψη μη απαραίτητων',
    customize: 'Προσαρμογή',
    savePreferences: 'Αποθήκευση',
    necessary: 'Απολύτως απαραίτητα',
    necessaryDesc: 'Απαιτούνται για την ασφάλεια και τη βασική λειτουργία.',
    analytics: 'Αναλύσεις & Απόδοση',
    analyticsDesc: 'Μας βοηθά να κατανοήσουμε τη χρήση του ιστότοπου.',
    marketing: 'Μάρκετινγκ',
    marketingDesc: 'Χρησιμοποιείται για τη μέτρηση της απήχησης των εκστρατειών.',
    preferences: 'Προτιμήσεις',
    preferencesDesc: 'Αποθηκεύει τη γλώσσα και τις ρυθμίσεις σας.',
    doNotSell: 'Μην πουλάτε τα προσωπικά μου δεδομένα',
    policyLinkText: 'Πολιτική Απορρήτου',
  },
  cs: {
    name: 'Czech',
    nativeName: 'Čeština',
    title: 'Vážíme si vašeho soukromí 🌿',
    description: 'Greenwave Society používá soubory cookie k vylepšení vašich zkušeností v souladu s GDPR.',
    acceptAll: 'Přijmout vše',
    rejectAll: 'Odmítnout nepovinné',
    customize: 'Upravit nastavení',
    savePreferences: 'Uložit nastavení',
    necessary: 'Nezbytně nutné',
    necessaryDesc: 'Vyžadováno pro bezpečnost a základní funkce.',
    analytics: 'Analytika a výkon',
    analyticsDesc: 'Pomáhá nám porozumět chování návštěvníků.',
    marketing: 'Marketing',
    marketingDesc: 'Slouží k měření dosahu kampaní.',
    preferences: 'Preferences',
    preferencesDesc: 'Ukládá preferovaný jazyk a zobrazení.',
    doNotSell: 'Neprodávat mé osobní údaje',
    policyLinkText: 'Zásady ochrany osobních údajů',
  },
  ro: {
    name: 'Romanian',
    nativeName: 'Română',
    title: 'Apreciem confidențialitatea dvs. 🌿',
    description: 'Greenwave Society folosește cookie-uri pentru a îmbunătăți experiența dvs. în conformitate cu GDPR.',
    acceptAll: 'Acceptă tot',
    rejectAll: 'Respinge neesențiale',
    customize: 'Personalizează',
    savePreferences: 'Salvează preferințele',
    necessary: 'Strict necesare',
    necessaryDesc: 'Necesare pentru securitate și funcții de bază.',
    analytics: 'Analiză și performanță',
    analyticsDesc: 'Ne ajută să înțelegem modul de utilizare a site-ului.',
    marketing: 'Marketing',
    marketingDesc: 'Utilizat pentru măsurarea impactului campaniilor.',
    preferences: 'Preferințe',
    preferencesDesc: 'Salvează limba și setările preferate.',
    doNotSell: 'Nu vindeți informațiile mele personale',
    policyLinkText: 'Politica de confidențialitate',
  },
  hu: {
    name: 'Hungarian',
    nativeName: 'Magyar',
    title: 'Nagyra értékeljük magánéletét 🌿',
    description: 'A Greenwave Society sütiket használ a felhasználói élmény javítására a GDPR-nak megfelelően.',
    acceptAll: 'Összes elfogadása',
    rejectAll: 'Nem elengedhetetlenek elutasítása',
    customize: 'Beállítások testreszabása',
    savePreferences: 'Beállítások mentése',
    necessary: 'Szigorúan szükséges',
    necessaryDesc: 'Szükséges a biztonsághoz és az alapvető működéshez.',
    analytics: 'Analitika és teljesítmény',
    analyticsDesc: 'Segít megérteni a látogatók viselkedését.',
    marketing: 'Marketing',
    marketingDesc: 'A kampányok elérésének mérésére szolgál.',
    preferences: 'Beállítások',
    preferencesDesc: 'Elmenti a választott nyelvet és beállításokat.',
    doNotSell: 'Ne adja el a személyes adataimat',
    policyLinkText: 'Adatvédelmi irányelvek',
  },
  uk: {
    name: 'Ukrainian',
    nativeName: 'Українська',
    title: 'Ми цінуємо вашу приватність 🌿',
    description: 'Greenwave Society використовує файли cookie для покращення вашого досвіду відповідно до GDPR.',
    acceptAll: 'Прийняти всі',
    rejectAll: 'Відхилити необов’язкові',
    customize: 'Налаштувати',
    savePreferences: 'Зберегти налаштування',
    necessary: 'Строго необхідні',
    necessaryDesc: 'Необхідні для безпеки та базових функцій.',
    analytics: 'Аналітика та продуктивність',
    analyticsDesc: 'Допомагає нам зрозуміти поведінку відвідувачів.',
    marketing: 'Маркетинг',
    marketingDesc: 'Використовується для вимірювання охоплення кампаній.',
    preferences: 'Налаштування',
    preferencesDesc: 'Зберігає обрану мову та параметри.',
    doNotSell: 'Не продавати мою особисту інформацію',
    policyLinkText: 'Політика конфіденційності',
  },
  vi: {
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    title: 'Chúng tôi coi trọng quyền riêng tư của bạn 🌿',
    description: 'Greenwave Society sử dụng cookie để cải thiện trải nghiệm và phân tích lưu lượng truy cập.',
    acceptAll: 'Chấp nhận tất cả',
    rejectAll: 'Từ chối không thiết yếu',
    customize: 'Tùy chỉnh cài đặt',
    savePreferences: 'Lưu tùy chọn',
    necessary: 'Nghiêm ngặt cần thiết',
    necessaryDesc: 'Bắt buộc cho bảo mật và chức năng cốt lõi.',
    analytics: 'Phân tích & Hiệu suất',
    analyticsDesc: 'Giúp chúng tôi hiểu cách khách truy cập tương tác.',
    marketing: 'Tiếp thị',
    marketingDesc: 'Dùng để đo lường phạm vi chiến dịch.',
    preferences: 'Tùy chọn chức năng',
    preferencesDesc: 'Lưu ngôn ngữ và cài đặt hiển thị của bạn.',
    doNotSell: 'Không bán thông tin cá nhân của tôi',
    policyLinkText: 'Chính sách bảo mật',
  },
  th: {
    name: 'Thai',
    nativeName: 'ไทย',
    title: 'เราให้ความสำคัญกับความเป็นส่วนตัวของคุณ 🌿',
    description: 'Greenwave Society ใช้คุกกี้เพื่อปรับปรุงประสบการณ์และวิเคราะห์การเข้าชมตาม GDPR',
    acceptAll: 'ยอมรับทั้งหมด',
    rejectAll: 'ปฏิเสธที่ไม่จำเป็น',
    customize: 'ปรับแต่งการตั้งค่า',
    savePreferences: 'บันทึกการตั้งค่า',
    necessary: 'จำเป็นอย่างยิ่ง',
    necessaryDesc: 'จำเป็นสำหรับความปลอดภัยและการทำงานพื้นฐาน',
    analytics: 'การวิเคราะห์และประสิทธิภาพ',
    analyticsDesc: 'ช่วยให้เราเข้าใจการใช้งานของผู้เข้าชม',
    marketing: 'การตลาด',
    marketingDesc: 'ใช้เพื่อวัดผลการเข้าถึงแคมเปญ',
    preferences: 'การตั้งค่าฟังก์ชัน',
    preferencesDesc: 'บันทึกภาษาและการตั้งค่าที่คุณชอบ',
    doNotSell: 'ห้ามขายข้อมูลส่วนตัวของฉัน',
    policyLinkText: 'นโยบายความเป็นส่วนตัว',
  },
  id: {
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    title: 'Kami menghargai privasi Anda 🌿',
    description: 'Greenwave Society menggunakan cookie untuk meningkatkan pengalaman dan menganalisis lalu lintas.',
    acceptAll: 'Terima Semua',
    rejectAll: 'Tolak Yang Tidak Esensial',
    customize: 'Sesuaikan Pengaturan',
    savePreferences: 'Simpan Preferensi',
    necessary: 'Sangat Diperlukan',
    necessaryDesc: 'Diperlukan untuk keamanan dan fungsi dasar situs.',
    analytics: 'Analistik & Performa',
    analyticsDesc: 'Membantu kami memahami cara pengunjung berinteraksi.',
    marketing: 'Pemasaran',
    marketingDesc: 'Digunakan untuk mengukur jangkauan kampanye.',
    preferences: 'Preferensi',
    preferencesDesc: 'Menyimpan bahasa dan pengaturan pilihan Anda.',
    doNotSell: 'Jangan Jual Informasi Pribadi Saya',
    policyLinkText: 'Kebijakan Privasi',
  },
  ms: {
    name: 'Malay',
    nativeName: 'Bahasa Melayu',
    title: 'Kami menghargai privasi anda 🌿',
    description: 'Greenwave Society menggunakan kuki untuk meningkatkan pengalaman anda dan menganalisis trafik.',
    acceptAll: 'Terima Semua',
    rejectAll: 'Tolak Yang Tidak Penting',
    customize: 'Sesuaikan Tetapan',
    savePreferences: 'Simpan Pilihan',
    necessary: 'Sangat Diperlukan',
    necessaryDesc: 'Diperlukan untuk keselamatan dan fungsi asas.',
    analytics: 'Analitik & Prestasi',
    analyticsDesc: 'Membantu kami memahami interaksi pelawat.',
    marketing: 'Pemasaran',
    marketingDesc: 'Digunakan untuk mengukur jangkauan kempen.',
    preferences: 'Pilihan',
    preferencesDesc: 'Menyimpan bahasa dan tetapan pilihan anda.',
    doNotSell: 'Jangan Jual Maklumat Peribadi Saya',
    policyLinkText: 'Dasar Privasi',
  },
  bn: {
    name: 'Bengali',
    nativeName: 'বাংলা',
    title: 'আমরা আপনার গোপনীয়তাকে মূল্যায়ন করি 🌿',
    description: 'Greenwave Society আপনার অফার অভিজ্ঞতা উন্নত করতে কুকি ব্যবহার করে।',
    acceptAll: 'সব গ্রহণ করুন',
    rejectAll: 'অপ্রয়োজনীয় প্রত্যাখ্যান করুন',
    customize: 'কাস্টমাইজ করুন',
    savePreferences: 'পছন্দ সংরক্ষণ করুন',
    necessary: 'জরুরী প্রয়োজনীয়',
    necessaryDesc: 'নিরাপত্তা এবং মৌলিক কাজের জন্য প্রয়োজন।',
    analytics: 'অ্যানালিটিক্স',
    analyticsDesc: 'দর্শনার্থীদের ব্যবহার বুঝতে সাহায্য করে।',
    marketing: 'মার্কেটিং',
    marketingDesc: 'ক্যাম্পেইনের কার্যকারিতা পরিমাপ করতে ব্যবহৃত।',
    preferences: 'পছন্দসমূহ',
    preferencesDesc: 'আপনার পছন্দের ভাষা ও সেটআপ সংরক্ষণ করে।',
    doNotSell: 'আমার ব্যক্তিগত তথ্য বিক্রি করবেন না',
    policyLinkText: 'গোপনীয়তা নীতি',
  },
  tl: {
    name: 'Tagalog',
    nativeName: 'Tagalog',
    title: 'Pinapahalagahan namin ang iyong privacy 🌿',
    description: 'Gumagamit ang Greenwave Society ng cookies upang mapabuti ang iyong karanasan alinsunod sa GDPR.',
    acceptAll: 'Tanggapin Lahat',
    rejectAll: 'Tanggihan ang Hindi Kinakailangan',
    customize: 'I-customize ang Setting',
    savePreferences: 'I-save ang Gusto',
    necessary: 'Lubos na Kinakailangan',
    necessaryDesc: 'Kailangan para sa seguridad at pangunahing function.',
    analytics: 'Analytiko at Performance',
    analyticsDesc: 'Tumutulong sa amin na maunawaan ang mga bisita.',
    marketing: 'Pemasaran/Marketing',
    marketingDesc: 'Ginagamit upang sukatin ang abot ng kampanya.',
    preferences: 'Mga Preferensya',
    preferencesDesc: 'Tinatago ang napiling wika at setting.',
    doNotSell: 'Huwag Ibenta ang Aking Impormasyon',
    policyLinkText: 'Patakaran sa Privacy',
  },
  he: {
    name: 'Hebrew',
    nativeName: 'עברית',
    title: 'אנו מעריכים את הפרטיות שלך 🌿',
    description: 'Greenwave Society משתמשת בעוגיות כדי לשפר את חווית הגלישה שלך בהתאם ל-GDPR.',
    acceptAll: 'אשר הכל',
    rejectAll: 'דחה שאינם הכרחיים',
    customize: 'התאם הגדרות',
    savePreferences: 'שמור העדפות',
    necessary: 'חיוני בהחלט',
    necessaryDesc: 'נדרש לאבטחה ולפונקציות בסיסיות.',
    analytics: 'אנליטיקה וביצועים',
    analyticsDesc: 'מסייע לנו להבין את פעילות המבקרים באתר.',
    marketing: 'שיווק',
    marketingDesc: 'משמש למדידת חשיפת הקמפיינים שלנו.',
    preferences: 'העדפות פונקציונליות',
    preferencesDesc: 'שומר את השפה וההגדרות הנבחרות.',
    doNotSell: 'אל תמכור את המידע האישי שלי',
    policyLinkText: 'מדיניות פרטיות',
  },
  fa: {
    name: 'Persian',
    nativeName: 'فارسی',
    title: 'ما به حریم خصوصی شما احترام می‌گذاریم 🌿',
    description: 'Greenwave Society برای بهبود تجربه کاربری شما از کوکی‌ها استفاده می‌کند.',
    acceptAll: 'پذیرش همه',
    rejectAll: 'رد غیرضروری‌ها',
    customize: 'سفارشی‌سازی',
    savePreferences: 'ذخیره تنظیمات',
    necessary: 'کاملاً ضروری',
    necessaryDesc: 'برای امنیت و کارکرد اصلی سایت الزامی است.',
    analytics: 'تحلیل و عملکرد',
    analyticsDesc: 'به ما در درک نحوه تعامل کاربران کمک می‌کند.',
    marketing: 'بازاریابی',
    marketingDesc: 'برای سنجش میزان دسترسی کمپین‌ها استفاده می‌شود.',
    preferences: 'ترجیحات',
    preferencesDesc: 'زبان و تنظیمات دیداری شما را ذخیره می‌کند.',
    doNotSell: 'اطلاعات شخصی من را نفروشید',
    policyLinkText: 'سیاست حفظ حریم خصوصی',
  },
  ca: {
    name: 'Catalan',
    nativeName: 'Català',
    title: 'Valorem la teva privacitat 🌿',
    description: 'Greenwave Society utilitza galetes per millorar la vostra experiència segons el RGPD.',
    acceptAll: 'Accepta-ho tot',
    rejectAll: 'Rebutja no essencials',
    customize: 'Personalitza',
    savePreferences: 'Desa les preferències',
    necessary: 'Estrictament necessàries',
    necessaryDesc: 'Requerides per a la seguretat i funcions bàsiques.',
    analytics: 'Analítica i rendiment',
    analyticsDesc: 'Ens ajuda a entendre la navegació dels usuaris.',
    marketing: 'Màrqueting',
    marketingDesc: 'Utilitzat per mesurar l’impacte de les campanyes.',
    preferences: 'Preferències',
    preferencesDesc: 'Desa l’idioma i la configuració preferida.',
    doNotSell: 'No venguis la meva informació personal',
    policyLinkText: 'Política de privacitat',
  },
  hr: {
    name: 'Croatian',
    nativeName: 'Hrvatski',
    title: 'Cijenimo vašu privatnost 🌿',
    description: 'Greenwave Society koristi kolačiće za poboljšanje vašeg iskustva u skladu s GDPR-om.',
    acceptAll: 'Prihvati sve',
    rejectAll: 'Odbij neobavezno',
    customize: 'Prilagodi postavke',
    savePreferences: 'Spremi postavke',
    necessary: 'Strogo neophodno',
    necessaryDesc: 'Potrebno za sigurnost i osnovno funkcioniranje.',
    analytics: 'Analitika i izvedba',
    analyticsDesc: 'Pomaže nam razumjeti interakciju posjetitelja.',
    marketing: 'Marketing',
    marketingDesc: 'Koristi se za mjerenje dosega kampanja.',
    preferences: 'Postavke',
    preferencesDesc: 'Sprema vaš željeni jezik i postavke.',
    doNotSell: 'Nemojte prodavati moje osobne podatke',
    policyLinkText: 'Pravila privatnosti',
  },
};
