"use client";

import { useCallback, useEffect, useState } from "react";
type Role = { id: string; name: string; description: string | null };
type User = { id: string; email: string; isActive: boolean; roles: Role[] };

export default function AdminUsersManager({ currentUserId }: { currentUserId: string }) {
  const [users, setUsers] = useState<User[]>([]); const [roles, setRoles] = useState<Role[]>([]);
  const [email, setEmail] = useState(""); const [newRoles, setNewRoles] = useState<string[]>([]); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/users", { cache: "no-store" }); if (response.ok) { const data = await response.json(); setUsers(data.users); setRoles(data.roles); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function create() { const response = await fetch("/api/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, roleIds: newRoles }) }); const data = await response.json(); setMessage(response.ok ? data.setup : data.error); if (response.ok) { setEmail(""); setNewRoles([]); await load(); } }
  async function save(user: User) { const response = await fetch(`/api/admin/users/${user.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isActive: user.isActive, roleIds: user.roles.map(role => role.id) }) }); const data = await response.json(); setMessage(response.ok ? "Administrator updated." : data.error); if (response.ok) await load(); }
  function setUser(userId: string, change: (user: User) => User) { setUsers(values => values.map(user => user.id === userId ? change(user) : user)); }
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold text-slate-900">Administrators and roles</h1><p className="text-sm text-slate-500">Owner-controlled access. Disabled accounts have their sessions revoked immediately.</p></header>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Add administrator</h2><div className="mt-4 grid gap-3 lg:grid-cols-[1fr_2fr_auto]"><input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="name@example.org" className="rounded-lg border p-2.5"/><div className="flex flex-wrap gap-2">{roles.map(role => <label key={role.id} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><input type="checkbox" checked={newRoles.includes(role.id)} onChange={() => setNewRoles(values => values.includes(role.id) ? values.filter(id => id !== role.id) : [...values, role.id])}/>{role.name}</label>)}</div><button onClick={() => void create()} disabled={!email || newRoles.length === 0} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm text-white disabled:opacity-50">Add</button></div></section>
    {message && <p className="rounded-lg bg-slate-100 p-3 text-sm" role="status">{message}</p>}
    <section className="space-y-3">{users.map(user => <div key={user.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium text-slate-900">{user.email}{user.id === currentUserId ? " (you)" : ""}</p><p className="text-xs text-slate-500">{user.isActive ? "Active" : "Disabled"}</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={user.isActive} disabled={user.id === currentUserId} onChange={event => setUser(user.id, value => ({ ...value, isActive: event.target.checked }))}/>Active</label></div><div className="mt-4 flex flex-wrap gap-2">{roles.map(role => <label key={role.id} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><input type="checkbox" disabled={user.id === currentUserId} checked={user.roles.some(value => value.id === role.id)} onChange={() => setUser(user.id, value => ({ ...value, roles: value.roles.some(item => item.id === role.id) ? value.roles.filter(item => item.id !== role.id) : [...value.roles, role] }))}/>{role.name}</label>)}</div>{user.id !== currentUserId && <button onClick={() => void save(user)} className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Save access</button>}</div>)}</section>
  </div>;
}
