import { NextResponse } from "next/server";
import { requireCareersExportAdmin } from "@/lib/careers-admin";
import { CAREER_ROLES, CAREER_SLUGS } from "@/lib/careers";
import { getDb } from "@/lib/db";

const columns=[['Reference','reference'],['Submitted','createdAt'],['Status','status'],['Full name','fullName'],['Email','email'],['Phone','phone'],['Location','location'],['Availability','availability'],['Why Greenwave','motivation'],['Relevant experience','relevantExperience'],['Collaboration style','collaborationStyle'],['Role response','roleResponse'],['Portfolio or profile','portfolioUrl']] as const;
function xml(value:unknown){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function sheet(name:string,rows:Record<string,unknown>[]){const header=columns.map(([label])=>`<Cell ss:StyleID="Header"><Data ss:Type="String">${xml(label)}</Data></Cell>`).join('');const data=rows.map(row=>`<Row>${columns.map(([,key])=>`<Cell ss:StyleID="Body"><Data ss:Type="String">${xml(row[key])}</Data></Cell>`).join('')}</Row>`).join('');return `<Worksheet ss:Name="${xml(name.slice(0,31))}"><Table><Row>${header}</Row>${data||'<Row><Cell><Data ss:Type="String">No applications yet</Data></Cell></Row>'}</Table></Worksheet>`}
export async function GET(){const admin=await requireCareersExportAdmin();if(!admin)return NextResponse.json({error:"You do not have permission to export applications."},{status:403});const applications=await getDb().careerApplication.findMany({orderBy:{createdAt:'desc'}});await getDb().auditLog.create({data:{action:"CAREER_APPLICATIONS_EXPORTED",actor:admin.email,actorUserId:admin.id,detail:`Exported ${applications.length} career applications`,resourceType:"career_application",outcome:"SUCCESS"}});const sheets=CAREER_SLUGS.map(slug=>sheet(CAREER_ROLES[slug].title.replace(' Communications',' Comms'),applications.filter(row=>row.roleSlug===slug))).join('');const workbook=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Header"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#14532D" ss:Pattern="Solid"/></Style><Style ss:ID="Body"><Alignment ss:WrapText="1" ss:Vertical="Top"/></Style></Styles>${sheets}</Workbook>`;return new NextResponse(workbook,{headers:{'Content-Type':'application/vnd.ms-excel; charset=utf-8','Content-Disposition':'attachment; filename="greenwave-careers-applications.xls"','Cache-Control':'no-store'}})}
