"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
const NAIROBI_OFFSET = "+03:00";
export default function EventCreator() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ slug: "", title: "", description: "", location: "", startsAt: "", endsAt: "", capacity: "" });
  async function create() {
    const response = await fetch("/api/admin/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, timezone: "Africa/Nairobi", capacity: form.capacity ? Number(form.capacity) : null, startsAt: new Date(`${form.startsAt}:00${NAIROBI_OFFSET}`).toISOString(), endsAt: new Date(`${form.endsAt}:00${NAIROBI_OFFSET}`).toISOString() }) });
    const data = await response.json(); setMessage(response.ok ? "Event created." : data.error); if (response.ok) { setOpen(false); router.refresh(); }
  }
  return <div className="rounded-xl border bg-white p-5"><button onClick={() => setOpen(!open)} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-medium text-white">{open ? "Close" : "Create event"}</button>{open && <div className="mt-4 grid gap-3 sm:grid-cols-2"><input placeholder="Title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="rounded-lg border p-2.5"/><input placeholder="Slug" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-") })} className="rounded-lg border p-2.5"/><textarea placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="rounded-lg border p-2.5 sm:col-span-2"/><input placeholder="Location" value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} className="rounded-lg border p-2.5"/><input type="number" min="1" placeholder="Capacity (optional)" value={form.capacity} onChange={e => setForm({ ...form, capacity: e.target.value })} className="rounded-lg border p-2.5"/><label className="text-sm">Starts (Africa/Nairobi)<input type="datetime-local" value={form.startsAt} onChange={e => setForm({ ...form, startsAt: e.target.value })} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="text-sm">Ends (Africa/Nairobi)<input type="datetime-local" value={form.endsAt} onChange={e => setForm({ ...form, endsAt: e.target.value })} className="mt-1 w-full rounded-lg border p-2.5"/></label><button disabled={!form.title || !form.slug || !form.description || !form.startsAt || !form.endsAt} onClick={() => void create()} className="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50">Save draft</button></div>}{message && <p className="mt-3 text-sm" role="status">{message}</p>}</div>;
}
