"use client";

import { useState } from "react";
import Link from "next/link";

const base = "w-full rounded-xl border border-zinc-300 px-4 py-3 text-sm outline-none focus:border-emerald-700 focus:ring-2 focus:ring-emerald-100";

export function ApplicationForm({ roleSlug, roleTitle, roleQuestion }: { roleSlug: string; roleTitle: string; roleQuestion: string }) {
  const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [reference,setReference]=useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form=new FormData(event.currentTarget); const body=Object.fromEntries(form.entries()); const response=await fetch("/api/apply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,roleSlug,consent:form.get("consent")==="on"})}); const data=await response.json(); setLoading(false); if(!response.ok){setError(data.error??"Could not save your application.");return} setReference(data.reference); }
  if(reference) return <div className="py-8 text-center"><div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 text-2xl text-emerald-700">✓</div><h2 className="font-serif text-3xl">Application received</h2><p className="mt-4 text-zinc-600">Thank you for applying for {roleTitle}. Keep this reference for your records.</p><code className="mt-5 inline-block rounded-lg bg-emerald-50 px-4 py-2 font-bold text-emerald-800">{reference}</code><div><Link href="/careers" className="mt-7 inline-block font-semibold text-emerald-800">Back to careers</Link></div></div>;
  return <form onSubmit={submit} className="space-y-10"><section><h2 className="font-serif text-3xl">About you</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field name="fullName" label="Full name"/><Field name="email" label="Email" type="email"/><Field name="phone" label="Phone number"/><Field name="location" label="Current location"/><label className="sm:col-span-2 text-sm font-semibold">Availability and time commitment<textarea name="availability" required rows={3} className={`${base} mt-2`} /></label><label className="sm:col-span-2 text-sm font-semibold">Portfolio or professional profile <span className="font-normal text-zinc-500">(optional)</span><input name="portfolioUrl" type="url" className={`${base} mt-2`} /></label></div></section><section className="border-t pt-9"><h2 className="font-serif text-3xl">Your contribution</h2><div className="mt-6 space-y-5"><Question name="motivation" label="Why do you want to contribute to Greenwave Society?"/><Question name="relevantExperience" label="What experience, skills, or lived perspective would you bring?"/><Question name="collaborationStyle" label="How do you communicate and collaborate when priorities or opinions differ?"/><Question name="roleResponse" label={roleQuestion}/></div></section><label className="flex gap-3 text-sm leading-6 text-zinc-600"><input name="consent" type="checkbox" required className="mt-1 h-4 w-4 accent-emerald-700"/>I confirm that the information is accurate and consent to Greenwave Society processing it for recruitment.</label>{error&&<p role="alert" className="rounded-lg bg-red-50 p-4 font-semibold text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-full bg-emerald-800 px-6 py-4 font-bold text-white disabled:opacity-60">{loading?"Submitting application":"Submit application"}</button></form>;
}

function Field({name,label,type="text"}:{name:string;label:string;type?:string}) { return <label className="text-sm font-semibold">{label}<input name={name} type={type} required className={`${base} mt-2`}/></label> }
function Question({name,label}:{name:string;label:string}) { return <label className="block text-sm font-semibold">{label}<textarea name={name} required rows={5} className={`${base} mt-2`}/></label> }
